# Generated by Django 6.0.3 on 2026-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_plate', models.CharField(max_length=10)),
                ('service_type', models.CharField(choices=[('Pressure', 'Pressure'), ('Puncture', 'Puncture'), ('Valve', 'Valve')], max_length=20)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
