# Generated by Django 6.0.3 on 2026-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('battery_type', models.CharField(choices=[('N70', 'N70'), ('N50', 'N50'), ('Dry Cell', 'Dry Cell'), ('Truck Battery', 'Truck Battery')], max_length=30)),
                ('service_type', models.CharField(choices=[('Hire', 'Hire'), ('Sale', 'Sale')], max_length=10)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
