# Generated by Django 6.0.3 on 2026-04-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryservice',
            name='battery_type',
            field=models.CharField(choices=[('Car Battey', 'Car Battery'), ('Truck Battery', 'Truck Battery')], max_length=30),
        ),
    ]
