# Generated by Django 6.0.3 on 2026-04-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_alter_batteryservice_battery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryservice',
            name='battery_type',
            field=models.CharField(choices=[('Car Battery', 'Car Battery'), ('Truck Battery', 'Truck Battery')], max_length=30),
        ),
    ]
