# Generated by Django 6.0.3 on 2026-04-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Personal Car'), ('Truck', 'Truck'), ('Taxi', 'Taxi'), ('Coaster', 'Coaster'), ('Boda', 'Boda-Boda')], max_length=10)),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('nin', models.CharField(max_length=14, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('is_parked', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
