# Generated by Django 6.0.3 on 2026-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicle_is_parked_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nin',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
