# Generated by Django 6.0.3 on 2026-04-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_vehicle_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
