# Generated by Django 6.0.3 on 2026-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_vehicle_nin_alter_vehicle_number_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Personal Car'), ('Motorcycle', 'Motorcycle'), ('Truck', 'Truck'), ('Taxi', 'Taxi'), ('Coaster', 'Coaster'), ('Boda', 'Boda-Boda')], max_length=10),
        ),
    ]
