# Generated by Django 6.0.3 on 2026-03-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('attendant', 'Parking Attendant'), ('manager', 'Section Manager '), ('admin', 'System Admin')], max_length=20),
        ),
    ]
