# Generated by Django 6.0.3 on 2026-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('attendant', 'Parking Attendant'), ('manager1', 'Section Manager1 '), ('manager2', 'Section Manager2 '), ('admin', 'System Admin')], max_length=20),
        ),
    ]
