# Generated by Django 6.0.3 on 2026-04-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
