# Generated by Django 6.0.3 on 2026-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('attendant', 'Parking Attendant'), ('manager1', 'Tyre Section Manager'), ('manager2', 'Battery Section Manager')], default='attendant', max_length=20, unique=True),
        ),
    ]
